const BotImperArr = [
    "ZCoin WalletUpdate BOT",
    "ZCoin Update BOT",
    "ZCoin UpdateBOT",
    "ZCoin NewsBOT",
    "ZCoin NewsBOT",
    "ZCoin WalletUpdateBOT",
    "ZCoin WаllеtUpdаtеВОТ",
    "ZСоin Nеws ВОТ",
    "ZСоin Nеws ВОТ",
    "Еnеrgі Nеws ВОТ",
    "Energi WalletUpdate BOT",
    "Energi Update BOT",
    "Energi UpdateBOT",
    "Energi NewsBOT",
    "Energi WalletUpdateBOT",
    "UpdаtеВОТ",
    "ZСоin Nеws ВОТ",
    "ZСоin Nеws ВОТ",
    "Enеrgі UpdаtеWаllеt ВОT" ,
    "Еnеrgі UpdаtеWаllеtВОT",
    "Enеrgі WаllеtUpdаtе ВОT",
    "Еnеrgі WаllеtUpdаtеВОT",
    "Еnеrgі Updаtе ВОT",
    "Еnеrgі Nеws ВОT",
    "Еnеrgі Nеws ВОT",
    "Еnеrgі UpdаtеWаllеtВОT",
    "Еnеrgі WаllеtUpdаtе ВОT",
    "Еnеrgі UpdаtеWаllеtВОT",
    "Еnеrgі WаllеtUpdаtеВОT",
    "Еnеrgі Nеws ВОT",
    "Еnеrgі UpdаtеWаllеtВОT",
    "Еnеrgі NеwsВОT",
    "ZCoin NеwsВОT",
    "Еnеrgі WаllеtUpdаtеВОT",
    "SmаrtСаsh WalletUpdateBOT",
    "SmаrtСаsh UpdateWallet BOT",
    "SmаrtСаsh Nеws ВОТ"
    ];
const NotBotArr= [
    "ZCoin Nеws",
    "CoinWallet",
    "Energi TipBot",
    "VitaeC",
    "[bsod.pw] I'm a BOT",
    "HeraBot",
    "Both",
    "aisha_botbaeva",
    "ProBoTHC",
    "autobot007",
    "spicybottle",
    "Garrett Abbott",
    "exbadabot1983",
    "HeraBot",
    "Zabotto",
    "Cryptobot",
    "Bad Robot",
    "[JuBot] tr91"
]
const BLNames = [
    "GiveawayBot",
    "Pump and dump",
    "Bitmex Giveaway",
    "pleinbit",
]
module.exports = {BotImperArr,NotBotArr,BLNames}